import type { Exercise } from '@/types'

export const exercises: Exercise[] = [
  // ── UPPER A ──────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: 'Barbell + Bench',
    category: 'compound',
    instructions: 'Lie flat on bench. Grip bar slightly wider than shoulder-width. Lower bar to lower chest with control. Press up explosively.',
    tips: 'Keep shoulder blades pinched together and feet flat. Slight arch in lower back is fine.',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'shoulders'],
    equipment: 'Barbell',
    category: 'compound',
    instructions: 'Hinge at hips ~45°, grip bar shoulder-width overhand. Pull bar to lower chest, squeezing shoulder blades. Lower with control.',
    tips: 'Keep back flat — do not round. Let the bar hang at arms length at bottom.',
  },
  {
    id: 'db-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps'],
    equipment: 'Dumbbells + Bench',
    category: 'compound',
    instructions: 'Sit upright, dumbbells at ear height, elbows at 90°. Press straight overhead until arms nearly locked. Lower with control.',
    tips: 'Do not flare elbows excessively. Keep core tight — do not arch lower back.',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    primary_muscle: 'back',
    secondary_muscles: ['biceps'],
    equipment: 'Cable Machine',
    category: 'compound',
    instructions: 'Grip bar wide overhand. Lean back slightly, pull bar to upper chest by driving elbows down and back. Return slowly.',
    tips: 'Think "elbows to back pockets". Do not shrug or use momentum.',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    primary_muscle: 'triceps',
    secondary_muscles: [],
    equipment: 'Cable Machine',
    category: 'isolation',
    instructions: 'Stand at cable, grip rope or bar. Keeping upper arms pinned to sides, extend forearms down fully. Return slowly.',
    tips: 'Upper arms must stay still throughout. Full lockout at bottom.',
  },
  {
    id: 'db-curl',
    name: 'Dumbbell Curl',
    primary_muscle: 'biceps',
    secondary_muscles: [],
    equipment: 'Dumbbells',
    category: 'isolation',
    instructions: 'Stand with dumbbells at sides, palms forward. Curl both up to shoulders. Lower slowly over 2–3 seconds.',
    tips: 'No swinging. Squeeze at the top. Supinate wrist as you curl up.',
  },

  // ── LOWER B ──────────────────────────────────────────────
  {
    id: 'low-bar-squat',
    name: 'Low-Bar Back Squat',
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'Barbell + Rack + Heel Plates',
    category: 'compound',
    instructions: 'Place bar ~5cm lower on traps than high bar. Wide stance, toes 30–45° out, heels on plates. Sit back into hips. Descend until thighs parallel. Drive up through heels.',
    tips: '⚠️ Your long femurs require this setup: wide stance + heel elevation. Forward lean is normal and correct for your anatomy. Do NOT try to stay fully upright — that is high-bar form and wrong for you.',
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back'],
    equipment: 'Barbell',
    category: 'compound',
    instructions: 'Hold bar at hip level. Push hips back (not down) while lowering bar along legs. Feel deep hamstring stretch. Drive hips forward to return.',
    tips: 'This is a hip hinge, not a squat. Soft bend in knees. Your long legs make this natural — push the hips BACK.',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: 'Leg Press Machine',
    category: 'compound',
    instructions: 'Place feet HIGH on platform, shoulder-width apart. Lower sled until 90° knee angle. Press to near lockout — do not lock knees hard.',
    tips: '⚠️ For your long legs: feet HIGH on platform shifts load to glutes/hamstrings. Never let lower back peel off the pad.',
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    primary_muscle: 'hamstrings',
    secondary_muscles: [],
    equipment: 'Leg Curl Machine',
    category: 'isolation',
    instructions: 'Lie face down. Curl legs to glutes. Squeeze at top. Lower slowly over 3 seconds.',
    tips: 'Do not lift hips off pad. Slow eccentric (lowering) is key.',
  },
  {
    id: 'calf-raise-standing',
    name: 'Standing Calf Raise',
    primary_muscle: 'calves',
    secondary_muscles: [],
    equipment: 'Calf Raise Machine or Step',
    category: 'isolation',
    instructions: 'Stand on edge of step or machine, heels hanging. Rise onto toes fully. Pause 1 second. Lower heels below platform level.',
    tips: 'Full range of motion is essential. Calves respond to stretch — do not skip the bottom portion.',
  },

  // ── UPPER D ──────────────────────────────────────────────
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: 'Dumbbells + Incline Bench',
    category: 'compound',
    instructions: 'Set bench to 30–45°. Press dumbbells from chest height up and slightly in. Lower with control to chest level.',
    tips: 'Do not go steeper than 45° — becomes shoulder press. Neutral wrists.',
  },
  {
    id: 'pull-up',
    name: 'Pull-up / Assisted Pull-up',
    primary_muscle: 'back',
    secondary_muscles: ['biceps'],
    equipment: 'Pull-up Bar or Assisted Machine',
    category: 'compound',
    instructions: 'Hang with overhand grip. Pull until chin clears bar by driving elbows down and back. Lower fully. Use assisted machine if needed.',
    tips: 'Full hang at bottom is mandatory. Do not kip. Use band or assisted machine to build up.',
    isAssisted: true,
  },
  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    primary_muscle: 'back',
    secondary_muscles: ['biceps'],
    equipment: 'Cable Machine',
    category: 'compound',
    instructions: 'Sit upright, knees slightly bent. Pull handle to lower sternum, elbows tight to body. Squeeze shoulder blades. Return slowly.',
    tips: 'Do not lean back and row — this cheats the movement. Torso stays almost vertical.',
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primary_muscle: 'shoulders',
    secondary_muscles: [],
    equipment: 'Dumbbells',
    category: 'isolation',
    instructions: 'Hold dumbbells at sides, slight bend in elbows. Raise arms to shoulder height leading with elbows. Lower slowly.',
    tips: 'Think "pour a glass of water" at the top (thumb slightly down). Keep traps relaxed.',
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    primary_muscle: 'triceps',
    secondary_muscles: ['chest'],
    equipment: 'Barbell + Bench',
    category: 'compound',
    instructions: 'Grip bar shoulder-width (narrower than normal bench). Lower to lower chest. Press up keeping elbows closer to body.',
    tips: 'Grip should still be outside shoulders — do not go too narrow or wrists suffer.',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    primary_muscle: 'biceps',
    secondary_muscles: [],
    equipment: 'Dumbbells',
    category: 'isolation',
    instructions: 'Hold dumbbells with neutral grip (thumbs up). Curl up without rotating wrist. Lower slowly.',
    tips: 'Trains brachialis and forearms. Alternate or simultaneous — both fine.',
  },

  // ── LOWER E ──────────────────────────────────────────────
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back', 'quads'],
    equipment: 'Barbell',
    category: 'compound',
    instructions: 'Wide stance, toes pointed ~45° out. Grip bar inside legs, shoulder-width. Sit hips down, chest up. Drive floor away, hips and shoulders rise together. Lock out standing tall.',
    tips: '⚠️ Recommended for your long-leg body type. Hips closer to bar, less lower-back stress than conventional. Push KNEES OUT over toes throughout.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: 'Bench + Dumbbells',
    category: 'compound',
    instructions: 'Place rear foot on bench. Front foot ~1.5× your leg length forward. Lower rear knee toward floor. Drive up through front heel.',
    tips: '⚠️ Your long legs need a LONGER stance than average. If your knee shoots past toes aggressively, step the front foot further forward.',
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    primary_muscle: 'glutes',
    secondary_muscles: ['hamstrings'],
    equipment: 'Barbell + Bench',
    category: 'compound',
    instructions: 'Sit against bench, bar over hips (pad it). Plant feet flat, shoulder-width. Drive hips up until body is horizontal. Squeeze glutes hard at top. Lower slowly.',
    tips: '⭐ This exercise works EXCEPTIONALLY well for your body type. Long femurs = greater hip extension range = more glute activation than most people get.',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    primary_muscle: 'quads',
    secondary_muscles: [],
    equipment: 'Leg Extension Machine',
    category: 'isolation',
    instructions: 'Adjust machine so knee joint aligns with pivot point. Extend legs fully. Pause 1 second. Lower slowly over 3 seconds.',
    tips: 'Do not kick up with momentum. Slow controlled reps with full extension.',
  },
  {
    id: 'calf-raise-seated',
    name: 'Seated Calf Raise',
    primary_muscle: 'calves',
    secondary_muscles: [],
    equipment: 'Seated Calf Raise Machine',
    category: 'isolation',
    instructions: 'Sit with knees under pad. Rise onto toes fully. Lower heels below platform.',
    tips: 'Seated targets soleus (deeper calf muscle). Different from standing. Do both.',
  },

  // ── UPPER C ──────────────────────────────────────────────
  {
    id: 'face-pull',
    name: 'Cable Face Pull',
    primary_muscle: 'shoulders',
    secondary_muscles: ['back'],
    equipment: 'Cable Machine',
    category: 'isolation',
    instructions: 'Set cable to upper-chest height with rope attachment. Pull rope to face, separating hands at the end so thumbs point behind you. Pause. Return slowly.',
    tips: '⭐ Best shoulder-health exercise in the program. Fixes internal rotation from too much pressing. Do these every Sunday without fail.',
  },
  {
    id: 'overhead-tricep-ext',
    name: 'Overhead Tricep Extension',
    primary_muscle: 'triceps',
    secondary_muscles: [],
    equipment: 'Dumbbell or Cable',
    category: 'isolation',
    instructions: 'Hold one dumbbell overhead with both hands (or cable with rope overhead). Lower behind head by bending elbows. Extend fully overhead. Keep elbows close to ears.',
    tips: 'Targets the long head of triceps — different from pushdown. Stretches the muscle under load for maximum growth stimulus.',
  },
  {
    id: 'incline-curl',
    name: 'Incline Dumbbell Curl',
    primary_muscle: 'biceps',
    secondary_muscles: [],
    equipment: 'Dumbbells + Incline Bench',
    category: 'isolation',
    instructions: 'Sit on incline bench (45°), arms hanging straight down. Curl both dumbbells up, keeping upper arms vertical. Squeeze at top. Lower fully for a deep stretch.',
    tips: '⭐ Best bicep exercise for the long head. The stretch at the bottom is the growth signal — do not cut range short.',
  },

  // ── WARM-UP ───────────────────────────────────────────────
  {
    id: 'goblet-squat',
    name: 'Goblet Squat (Warm-up)',
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'core'],
    equipment: 'Dumbbell or Kettlebell',
    category: 'compound',
    instructions: 'Hold dumbbell at chest. Wide stance, toes out 30–45°, heels slightly elevated. Squat as deep as possible keeping chest up. Drive up through heels.',
    tips: '⭐ This is your squat warm-up for weeks 1–4. Teaches upright torso with long femurs. Use light weight, focus on depth and control.',
  },
]

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id)
}
